# Generated by Django 2.1 on 2020-07-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField()),
                ('lifestyle', models.CharField(max_length=200, null=True)),
                ('big_cate', models.CharField(max_length=200, null=True)),
                ('sub_lifestyle', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=500, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='api.Store')),
            ],
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='detail_lifestyle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='img_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='map_lifestyle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='api.Store'),
        ),
    ]
